install.packages("tidyverse")
install.packages("arrow")
install.packages("DBI")
install.packages("duckdb")
install.packages ("duckplyr")
install.packages("devtools")
devtools::install_github("danicat/read.dbc")
install.packages("remotes")
remotes::install_github("rfsaldanha/microdatasus")
install.packages("read.dbc")